### PR TITLE
Use UTF-8 to decode downloaded async data

### PR DESCRIPTION
**Pull request by varunganesh91**
I encountered an issue where there are special non-ASCII characters (from foreign languages) in the analytics data that we download through the async API requests.

Adding this fix for it.

### CODE REVIEW

**Comment by tushdante** [comment]
Hey @varunganesh91  Thanks you for the PR! Could you provide a specific example that this PR is trying to fix? As far as I'm aware, there shouldn't be any foreign characters in a stats response.

**Comment by varunganesh91** [comment]
Hey @tushdante. The issue was happening when we were trying to `queue_async_stats_job` with the `segmentation_type` param as `KEYWORDS`. I believe some of the keywords defined would have foreign characters

**Comment by varunganesh91** [comment]
@tushdante Here's a snippet of the response we get:
```{
  "id": "ak9zr",
  "id_data": [
    {
      "segment": {
        "segment_name": "白ワイン",
        "segment_value": "1v5uo"
      },
    ...
    }
  ]
}```

**Comment by smaeda-ks** [comment]
Not sure why this wasn't merged into master after @tushdante approved. I did update the branch so now this can be merged.

**Pull request merged**
