### PR TITLE
Add `approval_status` as property on `Account`.

### PR DESCRIPTION
**Pull request by frewsxcv**
https://dev.twitter.com/ads/reference/get/accounts

### CODE REVIEW

**Comment by frewsxcv** [comment]
Disclaimer: I have not tested this.

**Comment by frewsxcv** [comment]
Test failures look unrelated.

**Comment by jaakko-sf** [comment]
Tests fixed in #81 

Changes in this PR Approved

**Comment by frewsxcv** [comment]
Tests pass now after merge.

**Comment by jaakko-sf** [comment]
CI should be fixed now after #89 merged in

**Comment by jaakko-sf** [comment]
Approved

**Pull request merged**
