### PR TITLE
Drop support for Python 3.2

### PR DESCRIPTION
**Pull request by juanshishido**
In reference to #87. Removing Python 3.2 from `.travis.yml`.

### CODE REVIEW

**Comment by jaakko-sf** [comment]
@juanshishido, can you also update `setup.py` to remove Python 3.2 references?

**Comment by frewsxcv** [comment]
There's also:

* https://github.com/twitterdev/twitter-python-ads-sdk/blob/master/docs/source/index.rst#compatibility--versioning
* https://github.com/twitterdev/twitter-python-ads-sdk/blob/master/README.rst#compatibility--versioning

**Comment by juanshishido** [comment]
Thanks for pointing that out, @frewsxcv!

**Comment by jaakko-sf** [comment]
Approved

**Pull request merged**
