### PR TITLE
Add new Line Item fields for MAP objectives

### LINKED ISSUE #263: New MAP LineItem fields
https://twittercommunity.com/t/announcement-breaking-changes-to-mobile-app-promotion-campaigns/140794

Do you plan to address these changes any time soon?

### PR DESCRIPTION
**Pull request by osowskit**
Adding new iOS and Android app store identifiers on the line items endpoint. [Announcement](https://twittercommunity.com/t/announcement-breaking-changes-to-mobile-app-promotion-campaigns/140794). This is part of the `line_item_apps` deprecation and that endpoint will be removed mid-Sept. 

**Note** existing values set on the `line_item_apps` will automatically be used by the line_items endpoint.

closes #263

### CODE REVIEW

**Comment by osowskit** [comment]
I still need to bump the version

**Comment by osowskit** [comment]
@tushdante could you help get this merged and release a new SDK?

**Review by tushdante — APPROVED** [review]
Might wanna check our tests to verify if things need to be updated there as well, but otherwise LGTM

**Comment by osowskit** [comment]
Cross fork CI builds won't work. Closing this and following up in #266

**Pull request closed without merging**
