### PR TITLE
Reference iteration variable

### PR DESCRIPTION
**Pull request by juanshishido**
`obj` instead of `object`

<sup>tiny PR</sup>

### CODE REVIEW

**Comment by juanshishido** [comment]
First off, sorry about combining changes for two unrelated issues into this PR. I didn't remember that pushing to `juanshishido:master` would add more commits to #86.

The latter parts of this PR are in reference to #70. b04245f adds tests and code for correctly formatting the time based on granularity. This failed for all of the Python 3 builds with an `ImportError` for the `support` module. (Not sure why this was not caught in a previous CI job.) 3391c89 makes the imports in `tests/test_client.py` absolute, fixing this issue.

Now, the build is failing for Python 3.2 only. The is due to a [recent change](https://github.com/kennethreitz/requests/pull/3385/files) to the Requests library. They are now using unicode literals, which causes a `SyntaxError` in Python 3.2 (see: [here](https://docs.python.org/release/3.0.1/whatsnew/3.0.html#text-vs-data-instead-of-unicode-vs-8-bit) and [here](https://pythonhosted.org/six/#six.u))&mdash;the `u'...'` prefix was reintroduced in Python 3.3. In terms of official support for Python 3.2, reviewers in [requests/#3385](https://github.com/kennethreitz/requests/pull/3385/files#r69560890) say they "dropped it like it was hot."

How should we proceed? cc: @twitterdev/ads-api-sdks

**Comment by hwz** [comment]
Since requests dropped support for 3.2 and we have pretty significant dependencies on the requests library, I think we should drop 3.2 support as well (especially given where it is in its lifecycle & adoption rate). Thoughts @jaakko-sf ?

**Comment by juanshishido** [comment]
Going to pull from upstream

**Comment by jaakko-sf** [comment]
approved

**Pull request merged**
