### PR TITLE
Fix `super` calls for error types.

### PR DESCRIPTION
**Pull request by frewsxcv**
Fixes https://github.com/twitterdev/twitter-python-ads-sdk/issues/61.

### CODE REVIEW

**Comment by frewsxcv** [comment]
@jaakko-sf Is there any chance this could get merged? We're seeing this quite a bit in our production code. I'm also available to help maintain this library if that's desired.

**Comment by juanshishido** [comment]
@frewsxcv: Thanks for following up and for your contributions and activity! I'll bring this up today during our team meeting. Will update you soon.

**Comment by frewsxcv** [comment]
Thanks @juanshishido! 🎉

**Comment by juanshishido** [comment]
@frewsxcv: We're going to review this PR this week and get back to you. Thanks!

**Comment by jaakko-sf** [comment]
Approved

**Pull request merged**
